"""empty message

Revision ID: c1c781cfde4e
Revises: 5bd0b4a738b9
Create Date: 2021-07-11 16:29:23.923266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c781cfde4e'
down_revision = '5bd0b4a738b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('created_date1', sa.String(length=64), nullable=True))
    op.drop_column('document', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('created_date', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('document', 'created_date1')
    # ### end Alembic commands ###
